AWSTemplateFormatVersion: '2010-09-09'
Description: 'Peer two VPCs'

Resources:
  VPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue Development-VPC
      PeerVpcId: vpc-0cdde8fb1c2492365
      PeerRegion: "ap-south-1"

