AWSTemplateFormatVersion: '2010-09-09'
Description: 'Peer two VPCs'

Resources:
  VPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue Development-VPC
      PeerVpcId: !ImportValue Production-VPC
  
  AcceptPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnectionAccepter
    Properties:
      VpcPeeringConnectionId: !Ref VPCPeeringConnection
